/**
 * cTrader HTML statement parser.
 *
 * Parses the "Account Statement" HTML export generated by the cTrader platform
 * (Account History → Export to HTML). Returns raw position rows for the
 * reconciler to group into ImportCandidates.
 *
 * Structural notes:
 *   - cTrader can export as a SINGLE table with section-header rows interspersed
 *     (section labels at full colspan) OR as MULTIPLE tables, one per section.
 *     This parser handles both by doing a linear scan of all rows in all tables,
 *     switching section context whenever it encounters a known section-label row.
 *   - Date format: "DD/MM/YYYY HH:MM:SS" (European, most common) or
 *     "MM/DD/YYYY HH:MM:SS" (some US-locale brokers) or "YYYY-MM-DD HH:MM:SS".
 *     The parser tries all three in order.
 *   - Balance/deposit rows (no symbol, no direction) are silently skipped.
 *   - Everything that can't be parsed is reported as an ImportParseError
 *     and NOT silently dropped.
 */

import type { ImportParseError } from '../../../../shared/types/index'

// ─── Section label sets (case-insensitive) ────────────────────────────────────

const CLOSED_LABELS = new Set([
  'closed positions',          // EN
  'posiciones cerradas',       // ES
  'geschlossene positionen',   // DE
  'positions fermées',         // FR
  'posições fechadas',         // PT
  'закрытые позиции',          // RU
  'closed',                    // some abbreviated exports
])

const OPEN_LABELS = new Set([
  'open positions',            // EN
  'posiciones abiertas',       // ES
  'offene positionen',         // DE
  'positions ouvertes',        // FR
  'posições abertas',          // PT
  'открытые позиции',          // RU
  'open',                      // some abbreviated exports
])

// ─── Raw row types ─────────────────────────────────────────────────────────────

/** A row from the Closed Positions table. */
export interface RawClosedPosition {
  positionId: string
  symbol: string
  direction: string     // "Buy" | "Sell" (raw, case-preserved)
  volumeLots: string
  openTimeMs: number    // UTC ms
  openPrice: string
  closeTimeMs: number   // UTC ms
  closePrice: string
  stopLoss: string      // "0" or "0.00000" if not set
  takeProfit: string    // "0" or "0.00000" if not set
  commission: string
  swap: string
  grossProfit: string
  netProfit: string
  label: string
}

/** A row from the Open Positions table. */
export interface RawOpenPosition {
  positionId: string
  symbol: string
  direction: string
  volumeLots: string
  openTimeMs: number
  openPrice: string
  stopLoss: string
  takeProfit: string
  commission: string
  swap: string
  label: string
}

export interface CTraderParseResult {
  readonly closedPositions: RawClosedPosition[]
  readonly openPositions: RawOpenPosition[]
  readonly errors: ImportParseError[]
}

// ─── Public entry point ────────────────────────────────────────────────────────

/** Parse a cTrader HTML statement string into raw position rows. */
export function parseCTraderHtml(html: string): CTraderParseResult {
  const errors: ImportParseError[] = []
  const closedPositions: RawClosedPosition[] = []
  const openPositions: RawOpenPosition[] = []

  // Extract all rows from all tables, in document order
  const allRows = extractAllRows(html)

  type Section = 'none' | 'closed' | 'open'
  let currentSection: Section = 'none'
  let colMap: ColMap = new Map()
  let rowIdxInSection = 0

  for (const row of allRows) {
    const cells = extractCells(row)
    if (cells.length === 0) continue

    // ── Check for section header row ─────────────────────────────────────────
    // A section header is a row whose single non-empty cell (often colspan=N)
    // contains a known section label.
    const nonEmpty = cells.filter((c) => c.length > 0)
    if (nonEmpty.length === 1) {
      const label = (nonEmpty[0] ?? '').toLowerCase().trim()
      if (CLOSED_LABELS.has(label)) {
        currentSection = 'closed'
        colMap = new Map()
        rowIdxInSection = 0
        continue
      }
      if (OPEN_LABELS.has(label)) {
        currentSection = 'open'
        colMap = new Map()
        rowIdxInSection = 0
        continue
      }
    }

    if (currentSection === 'none') continue

    // ── Check for column-header row ──────────────────────────────────────────
    // The first non-section-header row in each section is the column header.
    if (colMap.size === 0) {
      colMap = buildColMap(cells)
      rowIdxInSection = 0
      continue
    }

    // ── Data row ─────────────────────────────────────────────────────────────
    rowIdxInSection++

    // Skip balance/deposit/credit rows (no symbol or direction)
    const symbol    = cell(cells, colIdx(colMap, ...SYM_NAMES))
    const direction = cell(cells, colIdx(colMap, ...DIR_NAMES))
    if (!symbol || !direction) continue

    if (currentSection === 'closed') {
      const result = parseClosedRow(cells, colMap, rowIdxInSection)
      if (result.ok) {
        closedPositions.push(result.data)
      } else {
        errors.push({
          section: 'closed positions',
          rowIndex: rowIdxInSection,
          rawContent: cells.join(' | '),
          reason: result.reason,
        })
      }
    } else {
      const result = parseOpenRow(cells, colMap, rowIdxInSection)
      if (result.ok) {
        openPositions.push(result.data)
      } else {
        errors.push({
          section: 'open positions',
          rowIndex: rowIdxInSection,
          rawContent: cells.join(' | '),
          reason: result.reason,
        })
      }
    }
  }

  return { closedPositions, openPositions, errors }
}

// ─── Row / cell extraction ────────────────────────────────────────────────────

function extractAllRows(html: string): string[] {
  const rows: string[] = []
  const re = /<tr[^>]*>([\s\S]*?)<\/tr>/gi
  let m: RegExpExecArray | null
  while ((m = re.exec(html)) !== null) {
    rows.push(m[0])
  }
  return rows
}

function extractCells(row: string): string[] {
  const cells: string[] = []
  const re = /<t[dh][^>]*>([\s\S]*?)<\/t[dh]>/gi
  let m: RegExpExecArray | null
  while ((m = re.exec(row)) !== null) {
    cells.push(cellText(m[1]))
  }
  return cells
}

function cellText(html: string): string {
  return html
    .replace(/<[^>]+>/g, '')
    .replace(/&nbsp;/gi, ' ')
    .replace(/&#160;/gi, ' ')
    .replace(/&amp;/gi, '&')
    .replace(/&lt;/gi, '<')
    .replace(/&gt;/gi, '>')
    .replace(/&quot;/gi, '"')
    .replace(/&#39;/gi, "'")
    .replace(/\r?\n/g, ' ')
    .trim()
}

// ─── Column-index detection ───────────────────────────────────────────────────

type ColMap = Map<string, number>

function buildColMap(cells: string[]): ColMap {
  const map: ColMap = new Map()
  cells.forEach((c, i) => {
    const key = c.toLowerCase().replace(/\s+/g, ' ').trim()
    if (key) map.set(key, i)
  })
  return map
}

function colIdx(map: ColMap, ...names: string[]): number {
  for (const name of names) {
    const idx = map.get(name)
    if (idx !== undefined) return idx
  }
  return -1
}

function cell(cells: string[], idx: number): string {
  if (idx < 0 || idx >= cells.length) return ''
  return cells[idx] ?? ''
}

// ─── Known column-name variants ──────────────────────────────────────────────

const POS_ID_NAMES = [
  'position id', 'pos.id', '#', 'posición id', 'position-id', 'posid', 'id',
]
const SYM_NAMES = ['symbol', 'instrumento', 'instrument', 'pair', 'aktie']
const DIR_NAMES = [
  'direction', 'type', 'side', 'dirección', 'tipo',
  'richtung', 'sens', 'direção',
]
const VOL_NAMES = ['volume', 'qty', 'lots', 'volumen', 'menge', 'quantité', 'quantidade']
const OPEN_TIME_NAMES = [
  'open time', 'entry time', 'fecha apertura', 'öffnungszeit',
  'heure ouverture', 'hora abertura',
]
const OPEN_PRICE_NAMES = [
  'open price', 'entry price', 'precio apertura', 'eröffnungspreis',
  'prix ouverture', 'preço abertura',
]
const CLOSE_TIME_NAMES = [
  'close time', 'exit time', 'fecha cierre', 'schließzeit',
  'heure clôture', 'hora fecho',
]
const CLOSE_PRICE_NAMES = [
  'close price', 'exit price', 'precio cierre', 'schlusskurs',
  'prix clôture', 'preço fecho',
]
const SL_NAMES = ['s / l', 's/l', 'stop loss', 'sl', 'stop']
const TP_NAMES = ['t / p', 't/p', 'take profit', 'tp']
const COMM_NAMES = ['commission', 'kommission', 'comisión', 'comission']
const SWAP_NAMES = ['swap', 'финансирование']
const GROSS_NAMES = [
  'gross profit', 'gross p&l', 'gross p & l', 'ganancias brutas', 'brutto gewinn',
  'profit brut', 'lucro bruto', 'gross',
]
const NET_NAMES = [
  'net profit', 'net p&l', 'net p & l', 'ganancias netas', 'netto gewinn',
  'profit net', 'lucro líquido', 'profit', 'net',
]
const LABEL_NAMES = ['label', 'comment', 'comentario', 'kommentar', 'etiqueta', 'tag']
const CURRENT_PRICE_NAMES = [
  'current price', 'precio actual', 'aktueller kurs', 'prix actuel', 'preço atual',
]
const UNREALIZED_NAMES = [
  'unrealized p&l', 'unrealised p&l', 'unrealized profit', 'floating p/l',
  'ganancia flotante', 'schwebender gewinn',
]

// ─── Date parsing ─────────────────────────────────────────────────────────────

/**
 * Try three formats in order:
 *   1. DD/MM/YYYY HH:MM:SS  (European — most common)
 *   2. YYYY-MM-DD HH:MM:SS  (ISO)
 *   3. MM/DD/YYYY HH:MM:SS  (US — fallback, only used when day > 12 disambiguates)
 */
function parseCTraderDate(s: string): number | null {
  const trimmed = s.trim()

  // Format 1 & 3: d/m or m/d with slashes
  const slashMatch = trimmed.match(
    /^(\d{1,2})\/(\d{1,2})\/(\d{4})\s+(\d{2}):(\d{2}):(\d{2})$/,
  )
  if (slashMatch) {
    const a = slashMatch[1] ?? ''
    const b = slashMatch[2] ?? ''
    const year = slashMatch[3] ?? ''
    const h = slashMatch[4] ?? '0'
    const min = slashMatch[5] ?? '0'
    const sec = slashMatch[6] ?? '0'
    const aNum = parseInt(a, 10)
    const bNum = parseInt(b, 10)
    // If aNum > 12 it must be the day; use DD/MM.
    // If bNum > 12 it must be the day; use MM/DD.
    // If both ≤ 12, default to DD/MM (European).
    const [day, month] = bNum > 12 ? [bNum, aNum] : [aNum, bNum]
    if (month < 1 || month > 12 || day < 1 || day > 31) return null
    const ms = Date.UTC(+year, month - 1, day, +h, +min, +sec)
    return Number.isFinite(ms) ? ms : null
  }

  // Format 2: ISO YYYY-MM-DD HH:MM:SS
  const isoMatch = trimmed.match(
    /^(\d{4})-(\d{2})-(\d{2})\s+(\d{2}):(\d{2}):(\d{2})$/,
  )
  if (isoMatch) {
    const year  = isoMatch[1] ?? ''
    const month = isoMatch[2] ?? ''
    const day   = isoMatch[3] ?? ''
    const h     = isoMatch[4] ?? '0'
    const min   = isoMatch[5] ?? '0'
    const sec   = isoMatch[6] ?? '0'
    const ms = Date.UTC(+year, +month - 1, +day, +h, +min, +sec)
    return Number.isFinite(ms) ? ms : null
  }

  return null
}

// ─── Row parsers ──────────────────────────────────────────────────────────────

type ParseRowResult<T> =
  | { ok: true; data: T }
  | { ok: false; reason: string }

function parseClosedRow(
  cells: string[],
  map: ColMap,
  idx: number,
): ParseRowResult<RawClosedPosition> {
  void idx
  const positionId = cell(cells, colIdx(map, ...POS_ID_NAMES))
  const symbol     = cell(cells, colIdx(map, ...SYM_NAMES))
  const direction  = cell(cells, colIdx(map, ...DIR_NAMES))
  const volume     = cell(cells, colIdx(map, ...VOL_NAMES))
  const openTimeStr  = cell(cells, colIdx(map, ...OPEN_TIME_NAMES))
  const openPrice    = cell(cells, colIdx(map, ...OPEN_PRICE_NAMES))
  const closeTimeStr = cell(cells, colIdx(map, ...CLOSE_TIME_NAMES))
  const closePrice   = cell(cells, colIdx(map, ...CLOSE_PRICE_NAMES))
  const stopLoss     = cell(cells, colIdx(map, ...SL_NAMES))
  const takeProfit   = cell(cells, colIdx(map, ...TP_NAMES))
  const commission   = cell(cells, colIdx(map, ...COMM_NAMES))
  const swap         = cell(cells, colIdx(map, ...SWAP_NAMES))
  const grossProfit  = cell(cells, colIdx(map, ...GROSS_NAMES))
  const netProfit    = cell(cells, colIdx(map, ...NET_NAMES))
  const label        = cell(cells, colIdx(map, ...LABEL_NAMES))

  const issues: string[] = []
  if (!positionId)        issues.push('missing position ID')
  const openTimeMs  = parseCTraderDate(openTimeStr)
  const closeTimeMs = parseCTraderDate(closeTimeStr)
  if (!openTimeMs)  issues.push(`unparseable open time "${openTimeStr}"`)
  if (!closeTimeMs) issues.push(`unparseable close time "${closeTimeStr}"`)

  if (issues.length > 0) return { ok: false, reason: issues.join('; ') }

  return {
    ok: true,
    data: {
      positionId,
      symbol,
      direction,
      volumeLots: volume,
      openTimeMs:  openTimeMs as number,
      openPrice,
      closeTimeMs: closeTimeMs as number,
      closePrice,
      stopLoss:    stopLoss || '0',
      takeProfit:  takeProfit || '0',
      commission:  commission || '0',
      swap:        swap || '0',
      grossProfit: grossProfit || '0',
      netProfit:   netProfit || '0',
      label,
    },
  }
}

function parseOpenRow(
  cells: string[],
  map: ColMap,
  idx: number,
): ParseRowResult<RawOpenPosition> {
  void idx
  const positionId  = cell(cells, colIdx(map, ...POS_ID_NAMES))
  const symbol      = cell(cells, colIdx(map, ...SYM_NAMES))
  const direction   = cell(cells, colIdx(map, ...DIR_NAMES))
  const volume      = cell(cells, colIdx(map, ...VOL_NAMES))
  const openTimeStr = cell(cells, colIdx(map, ...OPEN_TIME_NAMES))
  const openPrice   = cell(cells, colIdx(map, ...OPEN_PRICE_NAMES))
  // Current price is present in open-positions but we don't need it
  void colIdx(map, ...CURRENT_PRICE_NAMES)
  void colIdx(map, ...UNREALIZED_NAMES)
  const stopLoss    = cell(cells, colIdx(map, ...SL_NAMES))
  const takeProfit  = cell(cells, colIdx(map, ...TP_NAMES))
  const commission  = cell(cells, colIdx(map, ...COMM_NAMES))
  const swap        = cell(cells, colIdx(map, ...SWAP_NAMES))
  const label       = cell(cells, colIdx(map, ...LABEL_NAMES))

  const issues: string[] = []
  if (!positionId) issues.push('missing position ID')
  const openTimeMs = parseCTraderDate(openTimeStr)
  if (!openTimeMs) issues.push(`unparseable open time "${openTimeStr}"`)

  if (issues.length > 0) return { ok: false, reason: issues.join('; ') }

  return {
    ok: true,
    data: {
      positionId,
      symbol,
      direction,
      volumeLots: volume,
      openTimeMs:  openTimeMs as number,
      openPrice,
      stopLoss:    stopLoss || '0',
      takeProfit:  takeProfit || '0',
      commission:  commission || '0',
      swap:        swap || '0',
      label,
    },
  }
}
