// @vitest-environment node
//
// Unit test: the cTrader protobuf codec (Wave 4 — docs/broker-integration.md §2.2
// / §8). Decodes RECORDED Spotware-wire ProtoMessage frames (tests/fixtures/broker/
// ctrader/execution-stream.json, generated by scripts/gen-ctrader-fixtures.cjs off
// the vendored schema) and asserts they normalise to the same BrokerEvents the
// adapter feeds the ingest service. Also round-trips the heartbeat + auth messages.
// No socket, no live Spotware — the codec is exercised against bytes (CLAUDE.md §19.10).

import { describe, it, expect } from 'vitest'
import { readFileSync } from 'fs'
import { join } from 'path'
import * as protobuf from 'protobufjs'
import { buildCtraderCodec, PROTO_FILES } from '../../../electron/services/broker/ctrader/codec'
import { mapExecutionEvent } from '../../../electron/services/broker/ctrader/mapper'
import {
  PAYLOAD,
  accountAuthResSchema,
  symbolsListResSchema,
} from '../../../electron/services/broker/ctrader/messages'
import type { CtraderSymbolInfo } from '../../../electron/services/broker/ctrader/mapper'

const PROTO_DIR = join(__dirname, '../../../resources/ctrader-proto')

interface Fixture {
  meta: { ctidTraderAccountId: number; positionId: number; symbolId: number; lotSize: number; t0: number }
  accountAuthRes: { payloadType: number; base64: string }
  symbolsListRes: { payloadType: number; base64: string }
  executions: Array<{ label: string; payloadType: number; base64: string }>
}

const FIXTURE = JSON.parse(
  readFileSync(join(__dirname, '../../fixtures/broker/ctrader/execution-stream.json'), 'utf-8'),
) as Fixture

const { lotSize: LOT, t0: T0, symbolId: SYMBOL_ID, positionId: POSITION_ID, ctidTraderAccountId: CTID } =
  FIXTURE.meta

/** A resolver that knows EURUSD's lot size (the adapter learns this from the symbol list). */
function resolveSymbol(id: number): CtraderSymbolInfo | null {
  return id === SYMBOL_ID ? { name: 'EURUSD', lotSizeCentiUnits: LOT } : null
}

const codec = buildCtraderCodec(protobuf, PROTO_DIR)
if (!codec) throw new Error('codec failed to build from the vendored schema')

const frameOf = (b64: string): Buffer => Buffer.from(b64, 'base64')

/** The recorded execution frame for a phase label, or throw if the fixture is missing. */
function execFrame(label: string): Buffer {
  const fx = FIXTURE.executions.find((e) => e.label === label)
  if (!fx) throw new Error(`missing execution fixture: ${label}`)
  return frameOf(fx.base64)
}

describe('cTrader codec — decode recorded execution frames', () => {
  it('maps the open fill to a position_opened BrokerEvent', () => {
    const msg = codec.decode(execFrame('open'))
    expect(msg.payloadType).toBe(PAYLOAD.OA_EXECUTION_EVENT)
    const event = mapExecutionEvent(msg.payload, { resolveSymbol, nowMs: 0 })
    expect(event).toEqual({
      type: 'position_opened',
      broker: 'ctrader',
      brokerAccountId: String(CTID),
      brokerTradeId: String(POSITION_ID),
      symbol: 'EURUSD',
      direction: 'long',
      volumeLots: 0.1,
      price: 1.085,
      stopLoss: 1.084,
      takeProfit: 1.087,
      eventTimeMs: T0,
      raw: msg.payload,
    })
  })

  it('maps the partial fill to a partial_close BrokerEvent', () => {
    const msg = codec.decode(execFrame('partial'))
    const event = mapExecutionEvent(msg.payload, { resolveSymbol, nowMs: 0 })
    expect(event?.type).toBe('partial_close')
    expect(event?.volumeLots).toBe(0.05)
    expect(event?.price).toBe(1.086)
    expect(event?.eventTimeMs).toBe(T0 + 60_000)
    expect(event?.brokerTradeId).toBe(String(POSITION_ID))
  })

  it('maps the closing fill to a position_closed BrokerEvent', () => {
    const msg = codec.decode(execFrame('close'))
    const event = mapExecutionEvent(msg.payload, { resolveSymbol, nowMs: 0 })
    expect(event?.type).toBe('position_closed')
    expect(event?.volumeLots).toBe(0.05)
    expect(event?.price).toBe(1.087)
    expect(event?.eventTimeMs).toBe(T0 + 120_000)
    // The closing position carried no protective orders → normalised to null.
    expect(event?.stopLoss).toBeNull()
    expect(event?.takeProfit).toBeNull()
  })

  it('decodes the account-auth response through its boundary schema', () => {
    const msg = codec.decode(frameOf(FIXTURE.accountAuthRes.base64))
    expect(msg.payloadType).toBe(PAYLOAD.OA_ACCOUNT_AUTH_RES)
    const parsed = accountAuthResSchema.safeParse(msg.payload)
    expect(parsed.success).toBe(true)
    expect(parsed.success && parsed.data.ctidTraderAccountId).toBe(CTID)
  })

  it('decodes the symbols-list response through its boundary schema', () => {
    const msg = codec.decode(frameOf(FIXTURE.symbolsListRes.base64))
    expect(msg.payloadType).toBe(PAYLOAD.OA_SYMBOLS_LIST_RES)
    const parsed = symbolsListResSchema.safeParse(msg.payload)
    expect(parsed.success).toBe(true)
    expect(parsed.success && parsed.data.symbol?.[0]?.symbolName).toBe('EURUSD')
  })

  it('returns an empty body for an inbound type Cairn does not consume', () => {
    // A heartbeat-shaped frame with no body still decodes to the tag (the adapter's
    // switch handles it); an unknown payload type must not throw.
    const frame = codec.encode({ payloadType: PAYLOAD.HEARTBEAT_EVENT, payload: {} })
    const msg = codec.decode(frame)
    expect(msg.payloadType).toBe(PAYLOAD.HEARTBEAT_EVENT)
  })

  it('throws on a frame that is not a valid ProtoMessage', () => {
    // Garbage bytes → decode throws; the connection catches and drops the frame.
    expect(() => codec.decode(Buffer.from([0xff, 0xff, 0xff, 0xff, 0xff]))).toThrow()
  })
})

describe('cTrader codec — round-trip encode/decode (heartbeat + auth)', () => {
  it('round-trips a heartbeat through encode → decode', () => {
    const frame = codec.encode({ payloadType: PAYLOAD.HEARTBEAT_EVENT, payload: {} })
    const msg = codec.decode(frame)
    expect(msg).toEqual({ payloadType: PAYLOAD.HEARTBEAT_EVENT, payload: {} })
  })

  it('encodes the application-auth request as valid wire bytes', () => {
    const frame = codec.encode({
      payloadType: PAYLOAD.OA_APPLICATION_AUTH_REQ,
      payload: { clientId: 'cid', clientSecret: 'secret' },
    })
    // The request types are not in the inbound (decode) table by design, so decode
    // the inner body independently with the same schema to prove the encode path.
    const root = protobuf.loadSync(PROTO_FILES.map((f) => join(PROTO_DIR, f)))
    const ProtoMessage = root.lookupType('ProtoMessage')
    const env = ProtoMessage.toObject(ProtoMessage.decode(frame), { bytes: Array }) as {
      payloadType: number
      payload: number[]
    }
    expect(env.payloadType).toBe(PAYLOAD.OA_APPLICATION_AUTH_REQ)
    const Req = root.lookupType('ProtoOAApplicationAuthReq')
    const body = Req.toObject(Req.decode(Uint8Array.from(env.payload))) as {
      clientId: string
      clientSecret: string
    }
    expect(body).toMatchObject({ clientId: 'cid', clientSecret: 'secret' })
  })

  it('encodes the account-auth request as valid wire bytes', () => {
    const frame = codec.encode({
      payloadType: PAYLOAD.OA_ACCOUNT_AUTH_REQ,
      payload: { ctidTraderAccountId: CTID, accessToken: 'access-token' },
    })
    const root = protobuf.loadSync(PROTO_FILES.map((f) => join(PROTO_DIR, f)))
    const ProtoMessage = root.lookupType('ProtoMessage')
    const env = ProtoMessage.toObject(ProtoMessage.decode(frame), { bytes: Array }) as {
      payloadType: number
      payload: number[]
    }
    expect(env.payloadType).toBe(PAYLOAD.OA_ACCOUNT_AUTH_REQ)
    const Req = root.lookupType('ProtoOAAccountAuthReq')
    const body = Req.toObject(Req.decode(Uint8Array.from(env.payload)), { longs: Number }) as {
      ctidTraderAccountId: number
      accessToken: string
    }
    expect(body).toMatchObject({ ctidTraderAccountId: CTID, accessToken: 'access-token' })
  })
})
